//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int ComId { get; set; }
        public string ComName { get; set; }
        public int CategId { get; set; }
        public string Discription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PictPath { get; set; }
        public byte[] PictBinary { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
